spring.application.name=backend

# MongoDB
spring.data.mongodb.uri=mongodb+srv://nipunnirman999_db_user:aau23aDg3CX8mr5a@cluster0.hngrg2g.mongodb.net/?appName=Cluster0

# Server
server.port=8080

# Jackson
spring.jackson.default-property-inclusion=non_null
